FROM node:16.15.1-alpine AS builder

WORKDIR /app

RUN corepack enable

COPY ./yarn.lock ./package.json ./.yarnrc.yml ./

RUN yarn install

COPY . .

RUN yarn build

FROM alpine as build

WORKDIR /app

COPY --from=builder /app/build .
